#!/usr/bin/env bash

SCRIPT_ROOT="$(cd -P "$( dirname "$SOURCE" )" && pwd )"

INIT_PATH="${SCRIPT_ROOT}/init"

for file in `\ls "${INIT_PATH}"`; do
  source "${INIT_PATH}/${file}"
done

# execute custom installation scripts
RECIPES_PATH="${SCRIPT_ROOT}/recipes"
source "${RECIPES_PATH}/sshd.sh" # install ssh server
source "${RECIPES_PATH}/zsh.sh"
source "${RECIPES_PATH}/zplug.sh"
source "${RECIPES_PATH}/ag.sh"
source "${RECIPES_PATH}/neovim.sh"
source "${RECIPES_PATH}/tmux.sh"
source "${RECIPES_PATH}/dotfiles.sh"
source "${RECIPES_PATH}/gnome-terminal.sh"
source "${RECIPES_PATH}/font-patch.sh"
source "${RECIPES_PATH}/rust.sh"
# exa.sh must include after rust.sh
source "${RECIPES_PATH}/exa.sh"

# version managers
source "${RECIPES_PATH}/rbenv.sh"
source "${RECIPES_PATH}/pyenv.sh"
source "${RECIPES_PATH}/nodenv.sh"
